const WIN_WIDTH = 500;
const WIN_HEIGHT = 500;
const ROT_SPEED = 8;

const PLAYER_WIDTH = 50;


module.exports = {
    WIN_HEIGHT: WIN_HEIGHT,
    WIN_WIDTH: WIN_WIDTH,
    ROT_SPEED : ROT_SPEED,
    PLAYER_WIDTH : PLAYER_WIDTH
}